bed_input_dir: results/bed
fq_input_dir: results/trim
output_dir: xrnas
cpus: 2
rna_ids:
- SRR5035944
- SRR9201799
- SRR9201801
- SRR9201803
- SRR9201805
- SRR9201807
annotation:
    annot_gtf: /mnt/lustre/asigorskikh/rnachrom/test_processing/data/genes/gencode.vM32.annotation.gtf
    strand_info: output_strand/mouse_strand_wins.tsv
hisat:
    genome: /mnt/lustre/asigorskikh/rnachrom/test_processing/data/mm10/mm10
    known_splice: /mnt/lustre/asigorskikh/rnachrom/test_processing/data/genes/gencode.vM32.ss
    hisat_threads: 8
stringtie:
    stringtie_threads: 8
    tool_path: output_strand/mouse_strand_wins.tsv
