bed_input_dir: results/bed
fq_input_dir: results/trim
output_dir: xrnas
cpus: 10
rna_ids:
- SRR5035944
- SRR5035946
- SRR9201799
- SRR9201801
- SRR9201803
- SRR9201805
- SRR9201807
- SRR9201809
- SRR9201811
- SRR9201813
- SRR9201815
- SRR9201817
- SRR9201819
- SRR9201821
- SRR9201823
- SRR9201825
- SRR9201827
- SRR9201829
annotation:
    gtf_annotation: /gpfs/asigorskikh/data/genes/gencode.vM32.annotation.gtf
    strand_info: strand/mouse_strand_wins.tsv
hisat:
    genome_path: /gpfs/asigorskikh/data/genomes/mm10/mm10
    known_splice: /gpfs/asigorskikh/data/genes/gencode.vM32.ss
    hisat_threads: 8
    cpus: 2
stringtie:
    stringtie_threads: 8
    cpus: 2
