bed_input_dir: results/bed
fq_input_dir: results/trim
output_dir: xrnas
cpus: 2
rna_ids:
- SRR9201799
- SRR9201801
- SRR9201803
- SRR9201805
- SRR9201807
annotation:
    gtf_annotation: /gpfs/asigorskikh/data/genes/gencode.vM32.annotation.gtf
    strand_info: strand/mouse_strand_wins.tsv
hisat:
    genome: /gpfs/asigorskikh/data/genomes/mm10/mm10
    known_splice: /gpfs/asigorskikh/data/genes/gencode.vM32.ss
    hisat_threads: 8
stringtie:
    stringtie_threads: 8
