rna_ids:
- SRR3633284
- SRR3633286
- SRR3633288
- SRR3633290
dna_ids:
- SRR3633285
- SRR3633287
- SRR3633289
- SRR3633291
base_dir: .
input_dir: /gpfs/asigorskikh/data/grid/gz
output_dir: new_results
cpus: 4
keep:
- contacts
- bed
- trim
rsites:
    type: grid
dedup:
    tool: fastq-dupaway
    tool_params:
        memlimit: 10240
        comparison: loose
align:
    cpus: 2
    tool: hisat2
    dna_genome_path: /gpfs/asigorskikh/data/genomes/hg38/hg38
    known_splice: /gpfs/asigorskikh/data/genes/gencode.v43.ss
    tool_threads: 8
stats:
    prefix: grid_human
