rna_ids:
- SRR5035944
- SRR5035946
dna_ids:
- SRR5035945
- SRR5035947
base_dir: .
input_dir: /gpfs/asigorskikh/data/grid/gz
output_dir: new_results
cpus: 2
keep:
- contacts
- bed
- trim
rsites:
    type: grid
dedup:
    tool: fastq-dupaway
    tool_params:
        memlimit: 10240
        comparison: loose
align:
    tool: hisat2
    dna_genome_path: /gpfs/asigorskikh/data/genomes/mm10/mm10
    known_splice: /gpfs/asigorskikh/data/genes/gencode.vM32.ss
    tool_threads: 8
stats:
    cpus: 8
    prefix: grid_mouse
