rna_ids:
- SRR9201799
- SRR9201801
- SRR9201803
- SRR9201805
- SRR9201807
dna_ids:
- SRR9201800
- SRR9201802
- SRR9201804
- SRR9201806
- SRR9201808
base_dir: .
input_dir: /gpfs/asigorskikh/data/radicl/gz
output_dir: new_results
cpus: 16
keep:
- contacts
- bed
- trim
rsites:
    type: skip
dedup:
    cpus: 4
    tool: fastq-dupaway
    params:
        memlimit: 10240
        compare: loose
trim:
    cpus: 5
    tool: trimmomatic
align:
    cpus: 2
    tool: hisat2
    dna_genome_path: /gpfs/asigorskikh/data/genomes/mm10/mm10
    known_splice: /gpfs/asigorskikh/data/genes/gencode.vM32.ss
    tool_threads: 8
contacts:
    cpus: 2
    mode: low-mem
stats:
    cpus: 8
    prefix: radicl
    mode: default
